### ISSUE TITLE
Catch invalid test file exceptions by JUnit

### ISSUE THREAD

**Issue by ninewise** [dodona-edu/judge-java#50]
```
Caused by org.junit.runners.model.InvalidTestClassError: Invalid test class 'PlaatsTestHidden':
  1. The class PlaatsTestHidden is not public.
  2. Test class should have exactly one public constructor
 at org.junit.runners.ParentRunner.validate(ParentRunner.java:430)
 at org.junit.runners.ParentRunner.<init>(ParentRunner.java:85)
 at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:68)
 at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
 at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:66)
 at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
 at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:66)
 at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:108)
 at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:94)
 at org.junit.runners.Suite.<init>(Suite.java:102)
 at org.junit.runners.Suite.<init>(Suite.java:70)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:108)
 at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
 at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:66)
 at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
 at org.junit.runner.Computer.getRunner(Computer.java:50)
 at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
 at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:66)
 at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:108)
 at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:94)
 at org.junit.runners.Suite.<init>(Suite.java:81)
 at org.junit.runner.Computer$2.<init>(Computer.java:33)
 at org.junit.runner.Computer.getSuite(Computer.java:28)
 at org.junit.runner.Request.classes(Request.java:75)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
 at dodona.junit.JUnitJSON.main(JUnitJSON.java:33)
```

As in https://dodona.ugent.be/en/submissions/6341733/

**Comment by ninewise** [comment]
Closed in 471c2795cf33d2fe9c877708735b0ed2fa518dba
